upstream django_backend {
    server backend:8000;
}

server {
    listen 80;
    server_name localhost;

    # Tamanho máximo de upload
    client_max_body_size 20M;

    # Logs
    access_log /var/log/nginx/sn_access.log;
    error_log  /var/log/nginx/sn_error.log;

    # Passa todas as requisições para o Django
    location / {
        proxy_pass         http://django_backend;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_redirect     off;
        proxy_read_timeout 90;
    }

    # Arquivos estáticos servidos diretamente pelo Nginx (mais rápido)
    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    # Arquivos de mídia
    location /media/ {
        alias /app/media/;
        expires 7d;
    }
}
