# Generated by Django 4.2.16 on 2026-06-02 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ['ordem', 'criado_em']},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['criado_em']},
        ),
        migrations.AlterModelOptions(
            name='historicotarefa',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AddField(
            model_name='tarefa',
            name='link_documento',
            field=models.URLField(blank=True, help_text='Cole aqui o link do Google Drive', verbose_name='Link do Documento (Drive)'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='prazo_dias',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Usado quando prazo_tipo = "days"', null=True, verbose_name='Prazo em dias'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='prazo_tipo',
            field=models.CharField(choices=[('fixed', 'Data fixa'), ('continuous', 'Contínua (sem prazo)'), ('days', 'Em X dias')], default='fixed', max_length=12, verbose_name='Tipo de Prazo'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historicotarefa',
            name='acao',
            field=models.CharField(choices=[('criou', 'Criou a tarefa'), ('editou', 'Editou a tarefa'), ('concluiu', 'Concluiu a tarefa'), ('reabriu', 'Reabriu a tarefa'), ('comentou', 'Comentou na tarefa'), ('checklist', 'Atualizou checklist'), ('timer', 'Registrou tempo')], max_length=20, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='historicotarefa',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historicotarefa',
            name='detalhe',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('cor', models.CharField(default='#C8A45E', max_length=7, verbose_name='Cor (hex)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SessaoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada')], default='ativa', max_length=12, verbose_name='Status')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado em')),
                ('finalizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('duracao_minutos', models.PositiveIntegerField(blank=True, help_text='Calculado automaticamente ao finalizar', null=True, verbose_name='Duração (minutos)')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='tasks.tarefa', verbose_name='Tarefa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_trabalho', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sessão de Trabalho',
                'verbose_name_plural': 'Sessões de Trabalho',
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.CreateModel(
            name='PausaSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pausado_em', models.DateTimeField(auto_now_add=True, verbose_name='Pausado em')),
                ('retomado_em', models.DateTimeField(blank=True, null=True, verbose_name='Retomado em')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pausas', to='tasks.sessaotarefa')),
            ],
            options={
                'ordering': ['pausado_em'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tarefa_vencendo', 'Tarefa vencendo em breve'), ('tarefa_atrasada', 'Tarefa atrasada'), ('comentario_novo', 'Novo comentário'), ('tarefa_concluida', 'Tarefa concluída'), ('tarefa_criada', 'Nova tarefa atribuída'), ('timer_lembrete', 'Lembrete de timer ativo')], max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='tasks.tarefa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='tarefa',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tarefas', to='tasks.tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='TarefaDependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('depende_de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerida_por', to='tasks.tarefa', verbose_name='Depende de')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias', to='tasks.tarefa', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Dependência',
                'verbose_name_plural': 'Dependências',
                'unique_together': {('tarefa', 'depende_de')},
            },
        ),
    ]
